--- #YAML:1.0
name:               HTTP-Cookies-Chrome
version:            0.99_07
abstract:           A subclass of HTTP::Cookies to handle Chrome
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:    0
    DBI:            0
    HTTP::Cookies:  0
    POSIX:          0
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
